#!/bin/bash
# Create for ItzLevvie && 0x4171341
# New funtions

function asciilogo {
version="1.01-beta"

clear
CYAN='\e[34m'
WHITE='\e[37m'
GREEN='\e[32m'
RED='\e[31m'
NC='\e[0m'

echo ""
echo -e "${CYAN}  This version is unstable"
echo -e "${CYAN}  may not work well"
echo -e "${CYAN}  has some bugs"
echo -e "${CYAN}  if you have the time you can collaborate"
echo -e "${CYAN}  with this work for the children of the house"
echo -e "${RED}                                           By ItzLevvie && 0x4171341 ${NC}"
echo -e "${RED}                                           Version: $version${NC}"
echo ""
}

function install () {
	asciilogo
	if [  -f "/etc/openjdk-8" ]; then
	         echo -e "\n${RED}[*]${NC} openjdk-8  is already installed
?\n"
	exit 1
	fi
	if [ `lsb_release -i | awk '{print $3}'` = Kali ] ||  [ `lsb_release -i | awk '{print $3}'` = 4nonOS ] && [ `lsb_release -i | awk '{print $3}'` = Ubuntu ] || [ `lsb_release -i | awk '{print $3}'` = Debian ] || [ `lsb_release -i | awk '{print $3}'` = Parrot ] || [ `lsb_release -i | awk '{print $3}'` = Raspbian ] || [ `lsb_release -i | awk '{print $3}'` = LinuxMint ]; then
		echo -e "\n${GREEN}[+]${NC} is already installed
...\n"
		apt-get update
		echo -e "\n${GREEN}[+]${NC} Installing dependencies...\n"
		apt-get install openjdk-8-jre
	else if  [ `lsb_release -i | awk '{print $3}'` = ManjaroLinux ] || [ `lsb_release -i | awk '{print $3}'` = Arch ] ; then
		echo -e "\n${GREEN}[+]${NC} is already installed
...\n"
		pacman -Syu
		echo -e "\n${GREEN}[+]${NC} Installing dependencies...\n"
		pacman -S --noconfirm openjdk-8-jre
	else
		echo ""
		echo -e "\n${RED}[*]${NC} Your distro is not currently supported \n"
		exit 1
		fi
	fi
  if [ ! -f /etc/arch-release ]
then
  echo "This script is running on Arch Linux!"
  echo "You want to continue anyway?"
  while true; do
    read -p "" yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit 0;;
        * ) echo "You want to continue anyway Yes o No [y|n].";;
    esac
  done

if [ "$(id -u)" == 0 ]; then
	echo "You should not run this script directly as root."
	exit 1
elif ! sudo -v; then
	echo "Please configure sudo correctly before running this script."
	exit 1

sudo apt update && sudo apt install -y openjdk-8-jre
mkdir Minecraft ../

cd Minecraft
wget -q s3.amazonaws.com/Minecraft.Download/launcher/Minecraft.jar
wget -q files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.1-14.22.0.2475/forge-1.12.1-14.22.0.2475-installer.jar
wget -q launcher.mojang.com/mc/launcher/jar/66d552b9ce72dc495a2ec8ef2dcfb7a1d407752c/launcher.jar.lzma && lzma -d launcher.jar.lzma
java -jar Minecraft.jar && java -jar forge-1.12.1-14.22.0.2475-installer.jar && java -jar Minecraft.jar

cd ~ && cd .minecraft && rm -d server-resource-packs launcher.jar launcher.pack.lzma launcher_profiles.json

cd ~ && cd .minecraft/libraries && mkdir -p ca/weblite/java-objc-bridge/1.0.0 && cd ca/weblite/java-objc-bridge/1.0.0
wget -q https://libraries.minecraft.net/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0.jar
wget -q https://libraries.minecraft.net/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0-natives-osx.jar

cd ~ && cd .minecraft/libraries/com/mojang/text2speech/1.10.3
wget -q https://libraries.minecraft.net/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar
wget -q https://libraries.minecraft.net/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-osx.jar

cd ~ && cd .minecraft/libraries && mkdir -p org/lwjgl/lwjgl/lwjgl/2.9.2-nightly-20140822 && cd org/lwjgl/lwjgl/lwjgl/2.9.2-nightly-20140822
wget -q https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl/2.9.2-nightly-20140822/lwjgl-2.9.2-nightly-20140822.jar

cd ~ && cd .minecraft/libraries && mkdir -p org/lwjgl/lwjgl/lwjgl_util/2.9.2-nightly-20140822 && cd org/lwjgl/lwjgl/lwjgl_util/2.9.2-nightly-20140822
wget -q https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl_util/2.9.2-nightly-20140822/lwjgl_util-2.9.2-nightly-20140822.jar

cd ~ && cd .minecraft/libraries && mkdir -p org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822 && cd org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822
wget -q https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822-natives-osx.jar

cd ~ && cd .minecraft/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209
wget -q https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar

#cd ~ && cd .minecraft/libraries/net/java/jinput/jinput-platform/2.0.5
#wget -q https://libraries.minecraft.net/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar
#wget -q https://libraries.minecraft.net/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
#cd ~
#mv .minecraft Documents && mv Downloads/launcher.jar Documents && cd Documents && zip -r -q -9 1e1d0feec727796c50c3527f83f83fc8.
#cd ~
